apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: heavy-computation-
spec:
  entrypoint: calculate-heavy-task
  templates:
  - name: calculate-heavy-task
    steps:
    - - name: fibonacci-sequence
        template: fibonacci-calc
        arguments:
          parameters:
          - name: number
            value: "100000"

  - name: fibonacci-calc
    inputs:
      parameters:
      - name: number
    container:
      image: python:3.9
      command: [python, -c]
      args: ["import sys; def fib(n): a, b = 0, 1; for _ in range(n): a, b = b, a + b; return a; print(fib(int(sys.argv[1])))", "{{inputs.parameters.number}}"]
      resources:
        limits:
          cpu: "4"
          memory: "4Gi"
